### PR TITLE
Move `puppeteer` to `devDependencies`

### LINKED ISSUE #137: This extension takes 450 MB on disk
The puppeteer node module includes a full Chromium. Maybe that should be a dev dependency?

### PR DESCRIPTION
**Pull request by Stanzilla**
This is to make sure it is not included in the extension bundle. Fixes #137

### CODE REVIEW

**Comment by qjebbs** [comment]
what's the benefit does this PR bring? Have you ever test it for `chromium` not download to `node_modules` with this change?

**Comment by Stanzilla** [comment]
It fixes the mentioned issue. The extension is now around 4mb instead of 200

**Comment by qjebbs** [comment]
I see, I forgot to delete the `chromium` after I tested the plugin, and published it.

I have two questions:

- With `puppeteer` set to devDependencies, it's still in the `node_modules`,  we will get the same `chromium` after my test in the dir `puppeteer/puppeteer `.
- The extension imports codes from the `puppeteer`, not only for `dev`, but `running`, so `chromium` is still bundled on publish if I forgot to delete `chromium` again.

Seems that set to devDependencies doesn't change the circumstances.

**Comment by LucasFA** [comment]
Now puppeteer isn't shipped to the user innecessarily, but yes, adding it to `devDependencies` does mean that it isn't shipped to the user. You don't need to manually delete it in a shell.

Check [vsce's documentation](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#using-.vscodeignore): it has a note indicating that devDependencies are automatically ignored, along with all the rest of files in .vscodeignore that are not needed at runtime

Same reasoning in general: everything that you need in order to test or build but not at runtime should go as a dev dependency

**Pull request closed without merging**
